<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="q3_orb.aspx.cs" Inherits="Sessional2_Q3.q3_orb" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Book Management</title>
    <style type="text/css">
        .highlight-cat3 { background-color: #FFFF99; } /* Light yellow */
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <asp:SqlDataSource 
            ID="SqlDataSourceBooks" 
            runat="server"
            ConnectionString=""
            SelectCommand="SELECT B_Id, B_Title, B_Author, B_Cat FROM Book"
            InsertCommand="INSERT INTO Book (B_Title, B_Author, B_Cat) VALUES (@Title, @Author, @Category)"
            UpdateCommand="UPDATE Book SET B_Title=@Title, B_Author=@Author, B_Cat=@Category WHERE B_Id=@B_Id"
            DeleteCommand="DELETE FROM Book WHERE B_Id=@B_Id"
        >
            <InsertParameters>
                <asp:Parameter Name="Title" Type="String" />
                <asp:Parameter Name="Author" Type="String" />
                <asp:Parameter Name="Category" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Title" Type="String" />
                <asp:Parameter Name="Author" Type="String" />
                <asp:Parameter Name="Category" Type="Int32" />
                <asp:Parameter Name="B_Id" Type="Int32" />
            </UpdateParameters>
            <DeleteParameters>
                <asp:Parameter Name="B_Id" Type="Int32" />
            </DeleteParameters>
        </asp:SqlDataSource>

        <asp:GridView 
            ID="GridViewBooks" 
            runat="server"
            DataSourceID="SqlDataSourceBooks"
            AutoGenerateColumns="False"
            DataKeyNames="B_Id"
            AutoGenerateEditButton="True"
            AutoGenerateDeleteButton="True"
            OnRowDataBound="GridViewBooks_RowDataBound"
        >
            <Columns>
                <asp:BoundField DataField="B_Id" HeaderText="Book Code" ReadOnly="True" />
                <asp:BoundField DataField="B_Title" HeaderText="Book Name" />
                <asp:BoundField DataField="B_Author" HeaderText="Author Name" />
                <asp:BoundField DataField="B_Cat" HeaderText="Category Code" />
            </Columns>
        </asp:GridView>

        <h3>Add Book</h3>
        <asp:TextBox ID="txtTitle" runat="server" placeholder="Book Name" />
        <asp:TextBox ID="txtAuthor" runat="server" placeholder="Author Name" />
        <asp:TextBox ID="txtCategory" runat="server" placeholder="Category Code" />
        <asp:Button ID="btnInsert" runat="server" Text="Add Book" OnClick="btnInsert_Click" />
        <asp:Label ID="lblMsg" runat="server" ForeColor="Red" /><br />
    </form>
</body>
</html>
