<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Students.aspx.cs" Inherits="Crud.Students" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Student CRUD</title>
</head>
<body>
    <form id="form1" runat="server">  
        <div>
            <asp:ObjectDataSource ID="ObjectDataSource1" runat="server"
                TypeName="StudentDAL"
                SelectMethod="GetAllStudents"
                InsertMethod="InsertStudent"
                UpdateMethod="UpdateStudent"
                DeleteMethod="DeleteStudent">

                <InsertParameters>
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="age" Type="Int32" />
                    <asp:Parameter Name="course" Type="String" />
                </InsertParameters>

                <UpdateParameters>
                    <asp:Parameter Name="studentID" Type="Int32" />
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="age" Type="Int32" />
                    <asp:Parameter Name="course" Type="String" />
                </UpdateParameters>

                <DeleteParameters>
                    <asp:Parameter Name="studentID" Type="Int32" />
                </DeleteParameters>
            </asp:ObjectDataSource>

            <asp:GridView ID="GridView1" runat="server" 
                DataSourceID="ObjectDataSource1"
                AutoGenerateColumns="False" 
                DataKeyNames="StudentID"
                AllowPaging="True" AllowSorting="True" 
                AutoGenerateEditButton="True" AutoGenerateDeleteButton="True">
                
                <Columns>
                    <asp:BoundField DataField="StudentID" HeaderText="ID" ReadOnly="True" />
                    <asp:BoundField DataField="Name" HeaderText="Name" />
                    <asp:BoundField DataField="Age" HeaderText="Age" />
                    <asp:BoundField DataField="Course" HeaderText="Course" />
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
